import Link from "next/link";
import { ArrowRight, Check, CircleDot, FileText, Search, Sparkles } from "lucide-react";
import type { Market } from "@/types";
import { articles, faqs, industries, processSteps, projects, services } from "@/data/site";
import { localizedHref } from "@/lib/site";
import { Accordion, Tabs } from "@/components/ui/interactive";
import { Badge, Button, Card, Container, SectionHeading } from "@/components/ui/core";
import { ContactForm, NewsletterForm, QuoteForm } from "@/components/forms/forms";

function PageHero({ eyebrow, title, description, market, cta = true }: { eyebrow: string; title: string; description: string; market: Market; cta?: boolean }) {
  return <section className="overflow-hidden border-b border-[var(--border)] bg-[radial-gradient(circle_at_80%_10%,#DDF4FF,transparent_38%),linear-gradient(#fff,#F6F8FC)]"><Container className="py-20 sm:py-28"><Badge>{eyebrow}</Badge><h1 className="mt-6 max-w-4xl text-balance text-4xl font-extrabold tracking-[-0.05em] text-[var(--navy)] sm:text-6xl">{title}</h1><p className="mt-6 max-w-3xl text-pretty text-lg leading-8 text-[var(--muted)] sm:text-xl">{description}</p>{cta && <div className="mt-8 flex flex-wrap gap-3"><Button href={localizedHref(market.countryCode, market.locale, "quote")} size="lg">Start your project</Button><Button href={localizedHref(market.countryCode, market.locale, "contact")} size="lg" variant="secondary">Talk to us</Button></div>}</Container></section>;
}

function FinalCta({ market }: { market: Market }) {
  return <section className="section-space bg-[var(--soft)]"><Container><div className="rounded-[2rem] bg-[var(--navy)] p-8 text-white sm:p-12"><h2 className="text-3xl font-bold sm:text-4xl">Tell us what you need.</h2><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">We will turn it into a clear, scalable solution built around your business.</p><Button href={localizedHref(market.countryCode, market.locale, "quote")} className="mt-7">Request a quote<ArrowRight className="size-4 rtl:rotate-180" /></Button></div></Container></section>;
}

export function ServicesPage({ market }: { market: Market }) {
  return <><PageHero eyebrow="Build · Automate · Grow" title="One team for everything your digital product needs." description="From websites and applications to intelligent workflows, payment experiences and creative production." market={market} /><section className="section-space bg-white"><Container>{(["build", "automate", "grow"] as const).map((group) => <div key={group} className="mb-14"><SectionHeading title={group[0]?.toUpperCase() + group.slice(1)} description={group === "build" ? "Create the product and experience." : group === "automate" ? "Connect systems and reduce repetitive work." : "Improve how the product reaches, serves and retains users."} /><div className="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.filter((service) => service.group === group).map((service) => <Card key={service.slug} className="p-6"><h3 className="text-xl font-bold text-[var(--navy)]">{service.title}</h3><p className="mt-3 leading-7 text-[var(--muted)]">{service.description}</p><Link className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-blue-700" href={localizedHref(market.countryCode, market.locale, `services/${service.slug}`)}>Explore service<ArrowRight className="size-4 rtl:rotate-180" /></Link></Card>)}</div></div>)}</Container></section><section className="section-space bg-[var(--soft)]"><Container><SectionHeading title="Which service fits your need?" /><div className="mt-8 grid gap-4 md:grid-cols-3">{[["I need the complete product", "Product design + development"], ["I want to reduce repetitive work", "Automation + scripts + integrations"], ["I want to accept payments", "Payment provider assessment + integration"]].map(([need, answer]) => <Card key={need} className="p-6"><p className="font-bold text-[var(--navy)]">{need}</p><p className="mt-5 text-blue-700">{answer}</p></Card>)}</div></Container></section><FinalCta market={market} /></>;
}

export function ServicePage({ market, slug }: { market: Market; slug: string }) {
  const service = services.find((item) => item.slug === slug);
  if (!service) return null;
  const builds: Record<string, string[]> = {
    "web-development": ["Corporate websites", "Landing pages", "Web portals", "Booking platforms", "Membership platforms", "Admin dashboards", "Multilingual websites", "Headless solutions", "Performance optimization"],
    "scripts-automation": ["Repetitive task automation", "Scheduled jobs", "API synchronization", "File processing", "Report generation", "Email workflows", "Data import and export", "Internal productivity tools", "Compliant public-data collection where legally allowed"],
    "ai-solutions": ["Customer assistants", "Internal assistants", "RAG knowledge systems", "Document processing", "Intelligent search", "Classification", "Recommendations", "AI workflow integration", "Human review flows"],
    "video-production": ["Product demos", "App showcase videos", "Social reels", "Explainer videos", "Motion graphics", "Video editing", "AI-assisted workflows", "Captions and localization"],
  };
  const capabilities = builds[slug] ?? [...service.capabilities, "Custom user journeys", "Secure integrations", "Quality assurance", "Localization", "Ongoing improvement"];
  return <><PageHero eyebrow={service.group} title={service.title} description={service.description} market={market} /><section className="section-space bg-white"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading title="What we can deliver" description="The exact scope is chosen after understanding your users, business model and constraints." /><div className="grid gap-3 sm:grid-cols-2">{capabilities.map((item) => <div key={item} className="flex gap-3 rounded-2xl bg-[var(--soft)] p-4 font-semibold text-[var(--navy)]"><Check className="size-5 shrink-0 text-emerald-600" />{item}</div>)}</div></div></Container></section><section className="section-space bg-[var(--soft)]"><Container><SectionHeading title="Who this is for" /><div className="mt-8 grid gap-4 md:grid-cols-3">{["A new product that needs a clear first release", "An existing product that needs improvement", "A growing business that needs connected systems"].map((item) => <Card key={item} className="p-6"><CircleDot className="size-6 text-blue-600" /><p className="mt-4 font-bold leading-7 text-[var(--navy)]">{item}</p></Card>)}</div></Container></section><section className="section-space bg-white"><Container><SectionHeading title="How delivery works" /><div className="mt-8 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{processSteps.slice(0, 4).map(([title, description], index) => <Card key={title} className="p-5"><span className="text-sm font-black text-blue-600">0{index + 1}</span><h3 className="mt-3 font-bold text-[var(--navy)]">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{description}</p></Card>)}</div></Container></section><section className="section-space bg-[var(--soft)]"><Container className="grid gap-10 lg:grid-cols-2"><SectionHeading title={`Questions about ${service.title.toLowerCase()}`} description="We scope around the actual need, not a pre-made package." /><Accordion items={faqs.slice(0, 4).map(({ question, answer }) => ({ question, answer }))} /></Container></section><FinalCta market={market} /></>;
}

export function AboutPage({ market }: { market: Market }) {
  const principles = ["Clarity before complexity", "The solution before the technology", "Design in service of the user", "Measurable quality", "Security and privacy", "Products designed to grow", "Honest communication"];
  return <><PageHero eyebrow="About MIRAAJ.TECH" title="We build technology closer to business goals." description="MIRAAJ.TECH exists to turn digital goals into products people can understand, use and grow with." market={market} /><section className="section-space bg-white"><Container className="grid gap-12 lg:grid-cols-2"><SectionHeading title="A practical view of digital work" description="A website, app or AI feature only matters when it solves the right problem. We begin with the objective, remove unnecessary complexity, then choose a technical path that can be maintained." /><Card className="p-8"><h2 className="text-2xl font-bold text-[var(--navy)]">Our vision</h2><p className="mt-4 text-lg leading-8 text-[var(--muted)]">Make high-quality digital product delivery clearer and more accessible for companies working across local and international markets.</p></Card></Container></section><section className="section-space bg-[var(--soft)]"><Container><SectionHeading title="Principles that guide the work" /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{principles.map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 font-bold text-[var(--navy)]"><Check className="size-5 text-emerald-600" />{item}</div>)}</div></Container></section><section className="section-space bg-white"><Container><SectionHeading title="Global delivery, local experience" description="Each market can adapt language, currency, formatting, content and payment considerations without claiming a local office where none exists." /></Container></section><FinalCta market={market} /></>;
}

export function ProcessPage({ market }: { market: Market }) {
  return <><PageHero eyebrow="Our process" title="A visible path from uncertainty to launch." description="Each phase has a clear purpose, the input we need from you and an outcome you can review." market={market} /><section className="section-space bg-white"><Container><ol className="grid gap-5">{processSteps.map(([title, description], index) => <li key={title} className="grid gap-5 rounded-3xl border border-[var(--border)] p-6 md:grid-cols-[70px_1fr_1fr] md:items-center"><span className="grid size-12 place-items-center rounded-full bg-blue-600 font-black text-white">{index + 1}</span><div><h2 className="text-xl font-bold text-[var(--navy)]">{title}</h2><p className="mt-2 leading-7 text-[var(--muted)]">{description}</p></div><div className="rounded-2xl bg-[var(--soft)] p-4 text-sm"><strong>What you receive</strong><p className="mt-1 text-[var(--muted)]">{index < 2 ? "A clear decision and documented direction." : index < 6 ? "A reviewable product increment and quality evidence." : "A controlled release and an improvement path."}</p></div></li>)}</ol></Container></section><section className="section-space bg-[var(--soft)]"><Container><SectionHeading title="No requirements document? No problem." description="We help you prepare it through focused discovery and practical questions." /><Button href={localizedHref(market.countryCode, market.locale, "quote")} className="mt-7">Start with your idea</Button></Container></section></>;
}

export function WorkPage({ market }: { market: Market }) {
  const categories = ["All", "Web", "Mobile", "AI", "Automation", "E-commerce", "Video", "Business systems"];
  return <><PageHero eyebrow="Concept portfolio" title="Ideas turned into thoughtful digital experiences." description="Until verified client work is published, every item here is clearly marked as a concept and includes no invented results." market={market} /><section className="section-space bg-white"><Container><Tabs items={categories.map((category) => ({ label: category, content: <div className="grid gap-6 md:grid-cols-2">{projects.filter((project) => category === "All" || project.category.includes(category)).map((project) => <Card key={project.slug} className="overflow-hidden"><div className={`aspect-[1.8] bg-gradient-to-br ${project.accent} p-8`}><div className="h-full rounded-2xl bg-white/25 p-5 backdrop-blur"><div className="h-4 w-24 rounded bg-white/70" /><div className="mt-6 h-24 rounded-xl bg-slate-950/65" /></div></div><div className="p-6"><Badge>Concept</Badge><h2 className="mt-4 text-2xl font-bold text-[var(--navy)]">{project.name}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{project.summary}</p><p className="mt-4 text-sm font-bold text-blue-700">{project.services.join(" · ")}</p></div></Card>)}</div> }))} /></Container></section></>;
}

export function PricingPage({ market }: { market: Market }) {
  const factors = ["Project scope", "Pages or screens", "Custom design", "Integrations", "Multiple languages", "AI capabilities", "Payment providers", "Support level", "Required timeline"];
  const models = [["Starter Scope", "A focused website, prototype or first release with clear boundaries."], ["Custom Product", "A tailored platform, application, AI workflow or connected system."], ["Continuous Partnership", "Ongoing product development, maintenance and improvement."]];
  return <><PageHero eyebrow="Pricing approach" title="Every project is different, so the estimate starts with the real need." description="We do not publish invented package prices. A useful estimate follows a clear scope and delivery model." market={market} /><section className="section-space bg-white"><Container><SectionHeading title="What shapes the estimate" /><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{factors.map((factor) => <div key={factor} className="flex items-center gap-3 rounded-2xl bg-[var(--soft)] p-4 font-semibold"><Check className="size-5 text-emerald-600" />{factor}</div>)}</div></Container></section><section className="section-space bg-[var(--soft)]"><Container><div className="grid gap-5 md:grid-cols-3">{models.map(([title, description]) => <Card key={title} className="p-7"><h2 className="text-2xl font-bold text-[var(--navy)]">{title}</h2><p className="mt-4 leading-7 text-[var(--muted)]">{description}</p><p className="mt-8 text-sm font-bold text-blue-700">Estimated after discovery</p></Card>)}</div></Container></section><FinalCta market={market} /></>;
}

export function QuotePage({ market }: { market: Market }) {
  return <><PageHero eyebrow="Request a quote" title="Tell us the goal. We will help shape the path." description="A simple guided form that keeps your progress in this browser session. No file is uploaded until a secure API is connected." market={market} cta={false} /><section className="section-space bg-[var(--soft)]"><Container className="max-w-4xl"><QuoteForm /></Container></section></>;
}

export function ContactPage({ market }: { market: Market }) {
  return <><PageHero eyebrow="Contact" title="Start with a clear conversation." description="Choose a business, support or partnership inquiry. Contact details remain hidden until real company data is configured." market={market} cta={false} /><section className="section-space bg-[var(--soft)]"><Container className="grid gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><SectionHeading title="How can we help?" description="We reply through the contact method you select once a secure endpoint and real contact channels are connected." /><div className="mt-7 grid gap-3">{["Business inquiry", "Support inquiry", "Partnership inquiry"].map((item) => <div key={item} className="rounded-2xl border border-[var(--border)] bg-white p-4 font-bold text-[var(--navy)]">{item}</div>)}</div></div><ContactForm /></Container></section></>;
}

export function FaqPage({ market }: { market: Market }) {
  const categories = [...new Set(faqs.map((item) => item.category))];
  return <><PageHero eyebrow="FAQ" title="Useful answers before your project begins." description="Browse common questions about projects, pricing, development, AI, payments, support and localization." market={market} cta={false} /><section className="section-space bg-white"><Container><div className="mb-8 flex items-center gap-3 rounded-2xl border border-[var(--border)] p-4 text-[var(--muted)]"><Search className="size-5" /><span>Browse by category below</span></div><Tabs items={categories.map((category) => ({ label: category, content: <Accordion items={faqs.filter((item) => item.category === category).map(({ question, answer }) => ({ question, answer }))} /> }))} /></Container></section><FinalCta market={market} /></>;
}

export function InsightsPage({ market, articleSlug }: { market: Market; articleSlug?: string }) {
  const article = articles.find((item) => item.slug === articleSlug);
  if (article) return <><PageHero eyebrow={`${article.category} · Demo article`} title={article.title} description={article.excerpt} market={market} cta={false} /><article className="section-space bg-white"><Container className="grid max-w-5xl gap-10 lg:grid-cols-[220px_1fr]"><aside className="h-fit rounded-2xl bg-[var(--soft)] p-5"><strong>On this page</strong><nav className="mt-4 grid gap-2 text-sm text-blue-700"><a href="#context">Context</a><a href="#decisions">Key decisions</a><a href="#next">Next step</a></nav></aside><div className="prose-copy"><Badge>Demo content</Badge><h2 id="context">Begin with the business context</h2><p>This demonstration article shows the intended reading layout. Real editorial content should be reviewed, dated and attributed before publication.</p><h2 id="decisions">Make decisions in the right order</h2><p>Start with the user, desired outcome and operational constraints. Technology choices become clearer after those foundations are understood.</p><h2 id="next">Define the smallest useful next step</h2><p>A focused first step creates evidence without pretending every question is already answered.</p></div></Container></article></>;
  return <><PageHero eyebrow="Insights" title="Practical thinking for digital products and growth." description="Demo articles showing the future editorial experience. They are clearly marked until real content is published." market={market} cta={false} /><section className="section-space bg-white"><Container><div className="mb-10 grid gap-5 rounded-3xl bg-[var(--navy)] p-7 text-white md:grid-cols-[1fr_auto] md:items-end"><div><Badge className="border-white/20 bg-white/10 text-sky-200">Demo newsletter</Badge><h2 className="mt-4 text-3xl font-bold">Useful product notes, without noise.</h2><p className="mt-3 text-slate-300">Frontend preview only. No subscription is stored yet.</p></div><NewsletterForm /></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{articles.map((item) => <Card key={item.slug} className="flex flex-col p-6"><div className="flex items-center justify-between"><Badge>Demo</Badge><span className="text-xs text-slate-500">{item.readingTime} min</span></div><h2 className="mt-5 text-xl font-bold leading-7 text-[var(--navy)]">{item.title}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{item.excerpt}</p><Link href={localizedHref(market.countryCode, market.locale, `insights/${item.slug}`)} className="mt-auto inline-flex items-center gap-2 pt-6 text-sm font-bold text-blue-700">Read demo article<ArrowRight className="size-4 rtl:rotate-180" /></Link></Card>)}</div></Container></section></>;
}

export function CareersPage({ market }: { market: Market }) {
  return <><PageHero eyebrow="Careers" title="Thoughtful work, clear collaboration." description="We value ownership, respectful communication, useful feedback and remote-friendly collaboration." market={market} cta={false} /><section className="section-space bg-white"><Container><div className="grid gap-5 md:grid-cols-3">{[["Clarity", "Decisions and expectations are documented."], ["Craft", "Quality includes usability, reliability and maintainability."], ["Collaboration", "Remote work succeeds through context and trust."]].map(([title, text]) => <Card key={title} className="p-6"><h2 className="text-xl font-bold text-[var(--navy)]">{title}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{text}</p></Card>)}</div><div className="mt-12 rounded-3xl border border-dashed border-slate-300 bg-[var(--soft)] p-10 text-center"><Sparkles className="mx-auto size-8 text-blue-600" /><h2 className="mt-4 text-2xl font-bold text-[var(--navy)]">No open roles are published right now.</h2><p className="mx-auto mt-3 max-w-xl text-[var(--muted)]">This is an honest empty state. A secure general application endpoint can be added when real hiring begins.</p></div></Container></section></>;
}

export function LegalPage({ market, kind }: { market: Market; kind: "privacy" | "terms" | "cookies" | "accessibility" }) {
  const content = {
    privacy: ["Privacy Policy", "This frontend does not collect inquiry data without a configured API. Market and consent preferences can be stored locally in your browser.", ["Information handling", "Forms validate data in the browser. Production submission remains disabled until a secure endpoint, retention policy and responsible legal entity are configured.", "Your choices", "You can choose necessary storage only. No analytics is active in this release."]],
    terms: ["Terms of Service", "This page is a structured placeholder and must be reviewed with the real legal entity, jurisdiction and service terms before commercial launch.", ["Service scope", "Each engagement should be governed by a written proposal or agreement.", "Acceptable use", "Services must not be used for unlawful automation, unauthorized access or provider-rule evasion."]],
    cookies: ["Cookie Policy", "Only preference storage is used in this frontend release. No analytics or advertising cookies are activated.", ["Necessary preferences", "miraaj_market remembers your chosen market. miraaj_consent stores your privacy choice.", "Future changes", "Optional tools must remain disabled until consent logic and this policy are updated."]],
    accessibility: ["Accessibility", "MIRAAJ.TECH aims for interfaces that can be used with keyboards, assistive technology and different motion preferences.", ["Current measures", "Semantic structure, visible focus, responsive layouts, reduced-motion support and associated form errors are included.", "Feedback", "An accessibility contact channel will appear when verified company contact details are configured."]],
  } as const;
  const [title, intro, sections] = content[kind];
  return <><PageHero eyebrow="Legal & standards" title={title} description={intro} market={market} cta={false} /><article className="section-space bg-white"><Container className="max-w-3xl"><Badge>Review before commercial launch</Badge><div className="prose-copy mt-8">{Array.from({ length: sections.length / 2 }, (_, index) => <section key={sections[index * 2]}><h2>{sections[index * 2]}</h2><p>{sections[index * 2 + 1]}</p></section>)}</div></Container></article></>;
}

export function StandardPage({ market, slug }: { market: Market; slug: string }) {
  const definitions: Record<string, [string, string, string]> = {
    solutions: ["Solutions", "Technology matched to a real operating goal.", "We combine product design, development, AI, automation, payments and support according to the outcome—not a generic package."],
    industries: ["Industries", "Useful digital experiences for different business contexts.", "Every industry has distinct users, workflows and constraints. We adapt the delivery without claiming expertise or compliance evidence we do not yet hold."],
    ai: ["AI solutions", "AI connected to useful work and clear human control.", "Assistants, knowledge search, document processing, recommendations and workflows designed around approved information."],
    payments: ["Payment solutions", "A clearer path to the right payment experience.", "We help assess and integrate suitable providers. Availability depends on country, business activity, company documents and provider approval."],
    video: ["Video & creative", "Show the product clearly, in motion.", "Product demos, app showcases, explainers, social content, motion graphics, editing, captions and localization."],
  };
  const page = definitions[slug] ?? ["Digital solutions", "Built around your business.", "A focused combination of strategy, design, technology and support."];
  return <><PageHero eyebrow={page[0]} title={page[1]} description={page[2]} market={market} /><section className="section-space bg-white"><Container><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{(slug === "industries" ? industries.map((item) => [item.title, item.description]) : services.slice(0, 6).map((item) => [item.title, item.description])).map(([title, description]) => <Card key={title} className="p-6"><FileText className="size-6 text-blue-600" /><h2 className="mt-4 text-xl font-bold text-[var(--navy)]">{title}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{description}</p></Card>)}</div></Container></section><FinalCta market={market} /></>;
}

export function renderMarketingPage({ market, segments }: { market: Market; segments: string[] }) {
  const [first, second] = segments;
  if (first === "services" && second) return <ServicePage market={market} slug={second} />;
  if (first === "services") return <ServicesPage market={market} />;
  if (first === "about") return <AboutPage market={market} />;
  if (first === "process") return <ProcessPage market={market} />;
  if (first === "work") return <WorkPage market={market} />;
  if (first === "pricing") return <PricingPage market={market} />;
  if (first === "quote") return <QuotePage market={market} />;
  if (first === "contact") return <ContactPage market={market} />;
  if (first === "faq") return <FaqPage market={market} />;
  if (first === "insights") return <InsightsPage market={market} articleSlug={second} />;
  if (first === "careers") return <CareersPage market={market} />;
  if (first === "privacy" || first === "terms" || first === "cookies" || first === "accessibility") return <LegalPage market={market} kind={first} />;
  return <StandardPage market={market} slug={first ?? "solutions"} />;
}
